service: frontend-fondos

provider:
  name: aws
  region: us-east-1

plugins:
  - serverless-finch

custom:
  client:
    bucketName: frontend-fondos-bucket-michael   
    distributionFolder: build                    
    indexDocument: index.html
    errorDocument: index.html
    acl: public-read                              
    tags:
      Project: frontend-fondos
